name: quiz_iso_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  syncfusion_flutter_charts: ^27.1.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
